@extends('layouts.app')
@section('title', 'Live budget')
@section('content')
<div class="budget-report">
<div class="page-heading"><div><span class="eyebrow">THE SPREADSHEET CAN TAKE A NAP</span><h1>{{ $year }} live budget</h1><p class="muted">Updated from invoices and bank activity whenever you open this page.</p></div><button class="button secondary no-print" data-print>Print report</button></div>
<div class="budget-actions no-print"><form class="filters" method="get"><label>Year<input name="year" type="number" min="2026" max="2099" value="{{ $year }}" required></label><button class="button secondary">View year</button></form><a href="{{ route('budget.review', ['year' => $year]) }}" class="button">Clarify transactions ({{ $report['needs_review'] }})</a><a href="{{ route('budget', ['mode' => 'archive']) }}">2022–2025 workbook archive</a></div>
<p class="small muted">{{ $report['transaction_count'] }} bank records{{ $report['first_date'] ? ', '.$report['first_date'].' through '.$report['last_date'] : '' }}. This is the available activity, not confirmation that the bank history is complete. Refunds offset the original income or expense category.</p>
@if($report['needs_review'])<div class="notice">{{ $report['needs_review'] }} transactions need clarification. Their amounts are included under uncategorized money in/out. Totals are provisional until possible transfers and other unknowns are resolved.</div>@endif
<div class="budget-summary">
@foreach([['Invoiced this year', 'billed', 'Charges issued, not cash received'], ['Still outstanding', 'outstanding', 'Current balance on this year’s invoices'], ['Expense plan', 'planned_expenses', $report['has_plan'] ? 'Saved annual plan' : 'No plan saved yet'], ['Operating money in', 'income', 'Bank cash, excluding confirmed transfers'], ['Operating money out', 'expenses', 'Bank cash, excluding confirmed transfers'], ['Operating cash surplus / deficit', 'net', 'Money in minus money out']] as [$label, $key, $caption])
<section class="stat {{ $key === 'net' ? 'accent' : '' }}"><span>{{ $label }}</span><strong>{{ $key === 'planned_expenses' && !$report['has_plan'] ? 'Not set' : \App\Support\Money::format($report[$key]) }}</strong><small>{{ $caption }}</small></section>@endforeach
</div>
@if($report['unlinkedPayments'])<div class="notice">{{ \App\Support\Money::format($report['unlinkedPayments']) }} in recorded payments has no bank transaction linked. These payments affect invoice balances but are not added again to bank cash flow. <a href="{{ route('admin.reconciliation') }}">Review payment matching</a>.</div>@endif
<section class="card"><h2>Monthly overview</h2><div class="table-wrap"><table><thead><tr><th>Month</th><th class="numeric">Invoiced</th><th class="numeric">Money in</th><th class="numeric">Money out</th><th class="numeric">Cash surplus / deficit</th></tr></thead><tbody>
@foreach($report['monthly'] as $month => $values)<tr><th>{{ array_values(\App\Services\BudgetReport::MONTHS)[$month - 1] }}</th>@foreach(['billed', 'income', 'expenses'] as $key)<td class="numeric">{{ \App\Support\Money::format($values[$key]) }}</td>@endforeach<td class="numeric strong">{{ \App\Support\Money::format($values['income'] - $values['expenses']) }}</td></tr>@endforeach
</tbody></table></div></section>
@foreach(['income' => 'Money in by category', 'expense' => 'Money out by category'] as $type => $heading)
<section class="card budget-section"><div class="section-heading"><h2>{{ $heading }}</h2><a class="small no-print" href="{{ route('budget.review', ['year' => $year, 'filter' => 'all']) }}">View / correct transactions →</a></div><div class="table-wrap budget-table-wrap" tabindex="0"><table class="budget-table"><thead><tr><th>Category</th>@foreach(\App\Services\BudgetReport::MONTHS as $month)<th class="numeric">{{ $month }}</th>@endforeach<th class="numeric">Total</th>@if($type === 'expense')<th class="numeric">Annual plan</th><th class="numeric">Plan remaining</th>@endif</tr></thead><tbody>
@foreach($report['rows'] as $key => $row)@if($row['type'] === $type)<tr><th>{{ $row['label'] }}</th>@foreach($row['months'] as $amount)<td class="numeric">{{ \App\Support\Money::format($amount) }}</td>@endforeach<td class="numeric strong">{{ \App\Support\Money::format($row['total']) }}</td>@if($type === 'expense')<td class="numeric">{{ $row['target'] !== null ? \App\Support\Money::format($row['target']) : 'Not set' }}</td><td class="numeric">{{ $row['target'] !== null ? \App\Support\Money::format($row['target'] - $row['total']) : '—' }}</td>@endif</tr>@endif @endforeach
</tbody></table></div></section>@endforeach
<section class="card"><h2>Invoice balances by unit</h2><p class="small muted">Invoices and payment allocations update these balances. Categorizing a bank receipt does not mark an invoice paid.</p><div class="table-wrap"><table><thead><tr><th>Unit</th><th class="numeric">Invoiced this year</th><th class="numeric">Paid / credited on invoices</th><th class="numeric">Still outstanding</th></tr></thead><tbody>@forelse($report['units'] as $unit => $values)<tr><th>Unit {{ $unit }}</th><td class="numeric">{{ \App\Support\Money::format($values['billed']) }}</td><td class="numeric">{{ \App\Support\Money::format($values['billed'] - $values['outstanding']) }}</td><td class="numeric">{{ \App\Support\Money::format($values['outstanding']) }}</td></tr>@empty<tr><td colspan="4">No invoices issued for this year yet.</td></tr>@endforelse</tbody></table></div></section>
<section class="card"><h2>Bank cash check</h2><p>Total deposits {{ \App\Support\Money::format($report['gross']['in']) }} · Total withdrawals {{ \App\Support\Money::format($report['gross']['out']) }}</p><p>Confirmed internal transfers: {{ \App\Support\Money::format($report['transfers']['in']) }} in / {{ \App\Support\Money::format($report['transfers']['out']) }} out. These are excluded from operating totals.</p><p class="small muted">Historical workbook transactions are not added to the live ledger. Manual receipts are not added again to bank deposits.</p></section>
@if(auth()->user()->is_admin && !session('impersonated_user_id'))<section class="card no-print"><details @if(!$report['has_plan']) open @endif><summary>Set the {{ $year }} expense plan</summary><p class="muted">{{ $plan['source'] }}. Annual targets are planning amounts; actual spending always comes from the bank.</p><form method="post" action="{{ route('admin.budget.plan') }}">@csrf<input type="hidden" name="year" value="{{ $year }}"><div class="budget-plan-fields">@foreach($categories as $key => [$label, $type])@if($type === 'expense')<label>{{ $label }}<input name="targets[{{ $key }}]" type="number" min="0" max="99999999.99" step="0.01" value="{{ old('targets.'.$key, isset($plan['targets'][$key]) ? number_format($plan['targets'][$key] / 100, 2, '.', '') : '') }}" placeholder="Not set"></label>@endif @endforeach</div><button class="button">Save expense plan</button></form></details></section>@endif
</div>
@endsection
