@extends('layouts.app')
@section('title', 'Clarify budget transactions')
@section('content')
<div class="page-heading"><div><a href="{{ route('budget.live', ['year' => $year]) }}">← {{ $year }} live budget</a><h1>What was that charge?</h1><p class="muted">Give mystery transactions a category. The budget updates immediately.</p></div></div>
<section class="card"><form class="filters" method="get"><label>Year<input name="year" type="number" min="2026" max="2099" value="{{ $year }}"></label><label>Show<select name="filter"><option value="pending">Needs clarification</option><option value="all" @selected(request('filter') === 'all')>All transactions</option></select></label><label>Description<input name="q" value="{{ request('q') }}"></label><button class="button secondary">Filter</button></form>
@if(auth()->user()->is_admin && !session('impersonated_user_id'))<form method="post" action="{{ route('admin.budget.suggest') }}">@csrf<input name="year" type="hidden" value="{{ $year }}"><button class="button">Ask AI for suggestions</button></form>@endif
<p class="small muted">Uses the provider and key in <a href="{{ route('admin.reconciliation') }}">AI settings</a>. Each run reviews up to 20 new transactions from this year, using descriptions, dates, amounts, invoice context, resident names, and previously confirmed categories and notes. Suggestions await your confirmation; no invoices are marked paid.</p>
@foreach($runs as $run)<p class="small">AI run #{{ $run->id }} · {{ $run->model }} · {{ ucfirst($run->status) }}{{ $run->error ? ': '.$run->error : '' }} @if(in_array($run->status, ['queued', 'processing']))<a href="{{ request()->fullUrl() }}">Refresh results</a>@endif</p>@endforeach</section>
@forelse($entries as $entry)@php($bank = $entry['bank'])@php($suggestion = $entry['suggestion'])
<section class="card"><div class="section-heading"><h2>{{ \App\Support\Money::format($bank->amount_cents) }}</h2><span class="small muted">{{ $bank->posted_on }} · {{ $bank->amount_cents >= 0 ? 'Money in' : 'Money out' }}</span></div><p class="strong">{{ $bank->description }}</p><p class="small muted">{{ $entry['source'] }}{{ $entry['category'] ? ': '.$categories[$entry['category']][0] : '' }}</p>
@if($entry['stale'])<div class="notice">The bank record changed since it was categorized. Review the new amount and description.</div>@endif
@if($bank->review_required)<div class="notice error">This bank transaction’s linked payment needs review before categorization. <a href="{{ route('admin') }}">Review payments in Administration</a>.</div>
@else
@if($suggestion?->suggested_category)<div class="notice"><strong>AI suggests: {{ $categories[$suggestion->suggested_category][0] ?? 'Needs more information' }}</strong> · {{ ucfirst($suggestion->confidence) }} confidence<p>{{ $suggestion->reason }}</p></div>@endif
@if(auth()->user()->is_admin && !session('impersonated_user_id'))<form method="post" action="{{ route('admin.budget.categorize', $bank->id) }}">@csrf<input type="hidden" name="fingerprint" value="{{ $entry['fingerprint'] }}"><div class="form-row"><label>Category<select name="category"><option value="">Still unknown</option>@foreach($categories as $key => [$label, $type])<option value="{{ $key }}" @selected($key === ($entry['category'] ?? $suggestion?->suggested_category))>{{ ucfirst($type) }} · {{ $label }}</option>@endforeach</select></label><label>Clarification / note<input name="note" maxlength="1000" value="{{ $suggestion?->note }}" placeholder="What was this for?"></label></div>
@if($bank->amount_cents < 0 && $categorizer->canRemember($bank->description))<p><label><input type="checkbox" name="remember" value="1"> Use this expense category for other existing and future debits with this exact vendor description.</label></p>@endif
<p class="small muted">For refunds, choose the original income or expense category. Only transfers between association accounts belong under Transfer.</p><button class="button">Confirm category</button></form>@endif
@endif</section>@empty<section class="card"><h2>No mystery transactions here.</h2><p>Try “All transactions” to review or correct existing categories.</p></section>@endforelse
{{ $entries->links() }}
@if($rules->isNotEmpty())<section class="card"><details><summary>Saved vendor rules</summary>@foreach($rules as $rule)<div class="budget-rule"><p>{{ $rule->description }} → {{ $categories[$rule->category][0] }}</p>@if(auth()->user()->is_admin && !session('impersonated_user_id'))<form method="post" action="{{ route('admin.budget.rule.delete', $rule->id) }}">@csrf @method('DELETE')<button class="button secondary">Remove rule</button></form>@endif</div>@endforeach</details></section>@endif
@endsection
