@extends('layouts.app')
@section('title', 'Invoice '.$invoice->number)
@section('content')
<div class="page-heading"><div><a href="{{ route('invoices') }}">← All invoices</a><h1>Invoice #{{ $invoice->number }}</h1></div><button class="button secondary no-print" data-print>Print invoice</button></div>
<section class="card invoice-paper"><div class="section-heading"><div><h2>1262 Bryn Mawr Association</h2><p class="muted">1262 W. Bryn Mawr Ave<br>Chicago, IL 60660</p></div><span class="badge {{ $invoice->status() }}">{{ ucfirst($invoice->status()) }}</span></div><div class="invoice-meta"><div><span class="eyebrow">BILLED TO</span><p>{{ $invoice->household->client_name }}<br>Unit {{ $invoice->unit_id }}</p></div><div><span class="eyebrow">ISSUED</span><p>{{ $invoice->issued_on->format('F j, Y') }}</p></div><div><span class="eyebrow">DUE</span><p>{{ $invoice->due_on->format('F j, Y') }}</p></div></div><table><thead><tr><th>Description</th><th class="numeric">Amount</th></tr></thead><tbody>@foreach($invoice->items as $item)<tr><td>{{ $item['name'] }}<small>{{ $item['description'] }}</small></td><td class="numeric">{{ \App\Support\Money::format($item['amount_cents']) }}</td></tr>@endforeach</tbody></table><div class="invoice-totals"><p>Total <strong>{{ \App\Support\Money::format($invoice->total_cents) }}</strong></p><p>Payments recorded <strong>{{ \App\Support\Money::format($invoice->historical_paid_cents + $invoice->allocatedCents()) }}</strong></p><p class="total">Remaining <strong>{{ \App\Support\Money::format($invoice->balanceCents()) }}</strong></p></div>@if($invoice->void_reason)<div class="notice">Voided: {{ $invoice->void_reason }}</div>@endif<h3>Payment information</h3><p class="muted preserve">{{ config('association.payment_instructions') }}</p>@foreach($payments as $payment)<p class="small">{{ $payment->paid_on }} @if($payment->payment_method) &middot; {{ \App\Services\PaymentService::METHODS[$payment->payment_method] ?? $payment->payment_method }} @endif · Payment applied: {{ \App\Support\Money::format($payment->amount_cents) }}</p>@endforeach @if($invoice->historical_paid_cents)<p class="small muted">Paid in FreshBooks{{ $invoice->paid_on ? ' on '.$invoice->paid_on->format('M j, Y') : '' }}.</p>@endif</section>
@if(auth()->user()->is_admin && !$invoice->void_reason)<details class="card no-print"><summary>Administrator actions</summary><p><a href="{{ route('admin.payment', $invoice->household_id) }}">Record a payment for this household →</a></p><form method="post" action="{{ route('admin.void', $invoice) }}" data-confirm="Void this invoice? Its history will remain available.">@csrf<label>Reason for voiding<input name="reason" required minlength="5"></label><button class="button danger">Void invoice</button></form></details>@endif
@if(auth()->user()->is_admin && !$invoice->void_reason && $invoice->balanceCents() > 0)
<section class="card no-print" id="record-payment"><h2>Mark this invoice as paid</h2><p>Record receipt of the remaining <strong>{{ \App\Support\Money::format($invoice->balanceCents()) }}</strong> for this invoice.</p><p class="small muted">This records a manual payment, without changing bank transactions or the bank balance. For a partial payment, an existing household credit, or a payment already imported from the bank, use <a href="{{ route('admin.payment', $invoice->household_id) }}">Record a payment</a> or <a href="{{ route('admin', ['tab' => 'payments']) }}">Apply household credit</a> instead.</p>
<form method="post" action="{{ route('admin.invoice.mark-paid', $invoice) }}" data-confirm="Confirm that the remaining invoice balance has been received?">@csrf<input type="hidden" name="request_key" value="{{ (string) \Illuminate\Support\Str::uuid() }}"><input type="hidden" name="expected_balance" value="{{ $invoice->balanceCents() }}"><div class="form-row"><label>Payment method<select name="payment_method" required><option value="">Choose a method</option>@foreach(\App\Services\PaymentService::METHODS as $value => $label)<option value="{{ $value }}" @selected(old('payment_method') === $value)>{{ $label }}</option>@endforeach</select></label><label>Payment received on<input type="date" name="paid_on" value="{{ old('paid_on', now('America/Chicago')->toDateString()) }}" max="{{ now('America/Chicago')->toDateString() }}" required></label><label>Payment reference / note<input name="note" value="{{ old('note') }}" placeholder="e.g. Zelle received, check #123" required minlength="3" maxlength="1000"></label></div><button class="button">Mark as paid</button></form><p class="small muted">Made a mistake? Reverse the payment under Administration &rarr; Payments.</p></section>
@endif
@endsection
