@extends('layouts.app')
@section('title', 'Administration')
@section('content')
<div class="page-heading"><div><span class="eyebrow">ASSOCIATION MANAGEMENT</span><h1>Administration</h1><p class="muted">A place for everything. Even the condo paperwork.</p></div></div>
@include('admin.tabs')
@if($tab === 'payments')
<section class="card"><h2>Record a payment</h2><p class="muted small">Choose a household to record a receipt and apply it to one or more invoices.</p>@foreach($households as $household)<a class="shortcut" href="{{ route('admin.payment', $household->id) }}">Unit {{ $household->unit_id }} · {{ $household->client_name }} <span>→</span></a>@endforeach</section>
<section class="card"><h2>Recent payments</h2><div class="table-wrap"><table><thead><tr><th>Household</th><th>Date</th><th>Amount</th><th>Record</th></tr></thead><tbody>@forelse($payments as $payment)<tr><td>{{ $payment->client_name }}</td><td>{{ $payment->paid_on }}@if($payment->payment_method)<small>{{ \App\Services\PaymentService::METHODS[$payment->payment_method] ?? $payment->payment_method }}</small>@endif</td><td>{{ \App\Support\Money::format($payment->amount_cents) }}</td><td>@if($payment->reversed_at)<span class="badge neutral">Reversed</span>@else<details><summary>Reverse payment</summary><form method="post" action="{{ route('admin.reverse', $payment->id) }}" data-confirm="Reverse this payment and restore invoice balances?">@csrf<label>Reason<input name="reason" required minlength="5"></label><button class="button danger">Reverse</button></form></details>@endif</td></tr>@empty<tr><td colspan="4" class="empty">No portal payments recorded yet. Historical paid invoices are preserved separately.</td></tr>@endforelse</tbody></table></div></section>
<section class="card"><h2>Apply household credit</h2><p class="small muted">Allocate previously recorded receipts to invoices without recording another payment.</p>@foreach($payments->whereNull('reversed_at') as $payment)<a class="shortcut" href="{{ route('admin.allocations', $payment->id) }}">{{ $payment->client_name }} · Receipt #{{ $payment->id }} · {{ \App\Support\Money::format($payment->amount_cents) }} <span>Manage allocations →</span></a>@endforeach</section>
@endif
@if($tab === 'billing')
<div class="notice">Recurring billing is <strong>{{ config('association.billing_enabled') ? 'enabled' : 'off' }}</strong>. Invoice emails are <strong>{{ config('association.invoice_emails_enabled') ? 'enabled' : 'off' }}</strong>. Starts {{ config('association.billing_start_month') ?: 'when configured' }} on day {{ config('association.billing_issue_day') }} each month, with payment due {{ config('association.billing_due_days') }} days later. <a href="{{ route('admin.reconciliation') }}">AI Reconcile &amp; settings</a></div>
<section class="card"><h2>Create a special assessment</h2><p class="small muted">Enter the building total. Unit shares: 1 = 14%, 2 = 21%, 3 = 21%, 4 = 21%, 5 = 23%.</p><form method="post" action="{{ route('admin.assessment.preview') }}">@csrf<label>Description<input name="title" required placeholder="e.g. Roof repair assessment"></label><div class="form-row"><label>Total assessment ($)<input name="amount" inputmode="decimal" required></label><label>Due date<input type="date" name="due_on" required min="{{ now()->toDateString() }}"></label></div><button class="button">Preview unit invoices</button></form></section>
<section class="card"><h2>Dues rates</h2><form method="post" action="{{ route('admin.dues') }}" class="filters">@csrf<label>Unit<select name="unit_id">@foreach($households as $household)<option value="{{ $household->unit_id }}">Unit {{ $household->unit_id }}</option>@endforeach</select></label><label>New monthly amount ($)<input name="amount" inputmode="decimal" required></label><label>Effective date<input type="date" name="effective_on" min="{{ now()->toDateString() }}" required></label><button class="button">Save dues rate</button></form><div class="table-wrap"><table><thead><tr><th>Unit</th><th>Effective</th><th>Monthly amount</th></tr></thead><tbody>@foreach($rates as $rate)<tr><td>{{ $rate->unit_id }}</td><td>{{ $rate->effective_on }}</td><td>{{ \App\Support\Money::format($rate->amount_cents) }}</td></tr>@endforeach</tbody></table></div></section>
<section class="card"><h2>Invoice email delivery</h2><p class="small muted">“Review required” means delivery was uncertain. Check the Resend delivery log before retrying manually.</p><div class="table-wrap"><table><thead><tr><th>Invoice</th><th>Resident ID</th><th>Status</th><th>Sent</th></tr></thead><tbody>@forelse($deliveries as $delivery)<tr><td>#{{ $delivery->number }}</td><td>{{ $delivery->user_id }}</td><td>{{ ucfirst(str_replace('_', ' ', $delivery->status)) }}</td><td>{{ $delivery->sent_at ?? '—' }}</td></tr>@empty<tr><td colspan="4" class="empty">No portal invoice emails queued yet.</td></tr>@endforelse</tbody></table></div></section>
@endif
@if($tab === 'residents')
<section class="card"><h2>Resident access</h2><p class="small muted">Updates revoke existing sessions. All active residents have administrator access.</p>@foreach($households as $household)@foreach($household->residents as $resident)<form class="resident-edit" method="post" action="{{ route('admin.resident', $resident) }}">@csrf<span class="pill">Unit {{ $household->unit_id }}</span><label>Name<input name="name" value="{{ $resident->name }}" required></label><label>Email<input type="email" name="email" value="{{ $resident->email }}" required></label><label>Phone<input name="phone" value="{{ $resident->phone }}"></label><label>Access<select name="active"><option value="1" @selected($resident->active)>Active</option><option value="0" @selected(!$resident->active)>Disabled</option></select></label><button class="button secondary">Save</button></form>@if($resident->active && $resident->id !== auth()->id())<form method="post" action="{{ route('admin.impersonate', $resident) }}">@csrf<button class="text-button">View as {{ $resident->name }}</button></form>@endif @endforeach @endforeach</section>
@endif
@if($tab === 'imports')
<section class="card"><h2>Import a CSV</h2><p class="muted small">Review changes before applying. Repeated transactions are skipped.</p><form method="post" action="{{ route('admin.preview') }}" enctype="multipart/form-data">@csrf<label>Export type<select name="kind"><option value="bank">BMO bank transactions</option><option value="invoices">FreshBooks invoice history</option></select></label><label>CSV file<input type="file" name="file" accept=".csv,.txt" required></label><button class="button">Preview import →</button></form></section>
<section class="card"><h2>Verify a bank balance</h2><p class="muted small">Use the posted end-of-day balance from a bank statement. Include all activity after this date in subsequent uploads.</p><form method="post" action="{{ route('admin.balance') }}">@csrf<div class="form-row"><label>As-of date<input type="date" name="as_of" required max="{{ now()->toDateString() }}"></label><label>Balance ($)<input name="amount" inputmode="decimal" required placeholder="0.00"></label></div><label>Statement or reference note<input name="note" required placeholder="e.g. September bank statement"></label><button class="button">Save verified balance</button></form></section>
<section class="card"><h2>Import history</h2>@forelse($imports as $import)<div class="history-item"><strong>{{ $import->filename }}</strong><small>{{ $import->created_at }} · {{ $import->status }}</small>@if(($import->path || $import->source_base64) && $import->status === 'preview')<a href="{{ route('admin.import', $import->id) }}">Review →</a>@endif</div>@empty<p class="muted">No imports yet.</p>@endforelse</section>
@endif
@if($tab === 'activity')
<section class="card"><h2>Activity log</h2>@forelse($events as $event)<div class="history-item"><strong>{{ str_replace('.', ' · ', $event->action) }}</strong><small>{{ $event->subject }} · {{ $event->created_at }}</small></div>@empty<p class="muted">Changes will appear here.</p>@endforelse</section>
@endif
@endsection
