@extends('layouts.app')
@section('title', 'AI reconciliation')
@section('content')
<div class="page-heading"><div><a href="{{ route('admin') }}">Back to administration</a><h1>Matchmaking for payments.</h1><p class="muted">AI suggests matches. You get the final say.</p></div></div>
<div class="admin-grid"><section class="card"><h2>AI settings</h2><p class="small muted">Choose OpenAI or Anthropic. A blank key keeps the saved key for that provider. Only administrators can manage these settings.</p>
<form method="post" action="{{ route('admin.ai.settings') }}">@csrf<label>Provider<select name="provider">@foreach($models as $provider => $model)<option value="{{ $provider }}" @selected($settings[$provider]['selected'] ?? false)>{{ ucfirst($provider) }} · {{ $model }}</option>@endforeach</select></label>
<label>API key<input type="password" name="api_key" autocomplete="new-password" maxlength="500" placeholder="Enter a new key or leave blank"></label>
<label>Saved key<select name="remove_key"><option value="0">Keep or replace key</option><option value="1">Remove this provider's key</option></select></label><button class="button">Save AI settings</button></form>
@foreach($models as $provider => $model)<p class="small">{{ ucfirst($provider) }}: {{ ($settings[$provider]['has_key'] ?? false) ? 'Key saved' : 'No key saved' }}{{ ($settings[$provider]['selected'] ?? false) ? ' · Selected' : '' }}</p>@endforeach</section>
<section class="card"><h2>Find possible matches</h2><p class="muted">Choose the dates of the bank credits to review.</p><p class="small">This sends transaction descriptions, dates, amounts, resident names and open invoice details to your selected AI provider. Provider API usage is billed to your account. Up to 80 credits and 100 open invoices per run.</p><p class="small muted">Already recorded payments and credits awaiting review are excluded. Imported receipts may already relate to paid FreshBooks invoices; check the payer and date before approving.</p>
<form method="post" action="{{ route('admin.reconciliation.start') }}">@csrf<div class="form-row"><label>From<input type="date" name="from" value="{{ old('from', now('America/Chicago')->subDays(90)->toDateString()) }}" required></label><label>To<input type="date" name="to" value="{{ old('to', now('America/Chicago')->toDateString()) }}" required></label></div><button class="button">AI Reconcile</button></form></section></div>
<section class="card"><h2>Reconciliation history</h2>@forelse($runs as $run)<a class="shortcut" href="{{ route('admin.reconciliation.run', $run->id) }}">Run #{{ $run->id }} · {{ $run->from_date }} to {{ $run->to_date }} · {{ ucfirst($run->provider) }} <span>{{ ucfirst($run->status) }}</span></a>@empty<p class="muted">No runs yet. Nothing has been matched behind your back.</p>@endforelse</section>
@endsection
