<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BuildingServiceController;
use App\Http\Controllers\GoogleAuthController;
use App\Http\Controllers\ImpersonationController;
use App\Http\Controllers\InvoiceEmailController;
use App\Http\Controllers\PlaidController;
use App\Http\Controllers\PortalController;
use App\Http\Controllers\ReconciliationController;
use App\Http\Middleware\ActiveResident;
use App\Http\Middleware\Administrator;
use Illuminate\Support\Facades\Route;

Route::middleware('guest')->group(function () {
    Route::get('/auth/google', [GoogleAuthController::class, 'redirect'])->middleware('throttle:10,1')->name('google.redirect');
    Route::view('/login', 'auth.login')->name('login');
    Route::post('/login', [AuthController::class, 'requestCode'])->middleware('throttle:5,1')->name('login.send');
    Route::view('/login/verify', 'auth.verify')->name('login.verify');
    Route::post('/login/verify', [AuthController::class, 'verify'])->middleware('throttle:10,1')->name('login.check');
});
Route::get('/auth/google/callback', [GoogleAuthController::class, 'callback'])->middleware('throttle:20,1')->name('google.callback');
Route::middleware(['auth', ActiveResident::class])->group(function () {
    Route::post('/impersonation/stop', [ImpersonationController::class, 'stop'])->name('impersonation.stop');
    Route::get('/auth/google/link', [GoogleAuthController::class, 'redirect'])->middleware('throttle:10,1')->name('google.link');
    Route::get('/', [PortalController::class, 'dashboard'])->name('dashboard');
    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
    Route::get('/invoices', [PortalController::class, 'invoices'])->name('invoices');
    Route::get('/invoices/{invoice}', [PortalController::class, 'invoice'])->whereNumber('invoice')->name('invoice');
    Route::get('/finances', [PortalController::class, 'finances'])->name('finances');
    Route::get('/directory', [PortalController::class, 'directory'])->name('directory');
    Route::view('/documents', 'documents')->name('documents');
    Route::get('/services', [BuildingServiceController::class, 'index'])->name('services');
    Route::middleware(Administrator::class)->prefix('admin')->group(function () {
        Route::get('/', [AdminController::class, 'index'])->name('admin');
        Route::post('/invoice-emails/preview', [InvoiceEmailController::class, 'preview'])->name('admin.invoice-emails.preview');
        Route::post('/invoice-emails/send', [InvoiceEmailController::class, 'send'])->middleware('throttle:5,1,invoice-emails')->name('admin.invoice-emails.send');
        Route::post('/impersonate/{user}', [ImpersonationController::class, 'start'])->whereNumber('user')->name('admin.impersonate');
        Route::get('/services', [BuildingServiceController::class, 'settings'])->name('admin.services');
        Route::get('/services/new', [BuildingServiceController::class, 'edit'])->name('admin.services.new');
        Route::get('/services/{service}/edit', [BuildingServiceController::class, 'edit'])->whereNumber('service')->name('admin.services.edit');
        Route::post('/services', [BuildingServiceController::class, 'save'])->name('admin.services.create');
        Route::post('/services/{service}', [BuildingServiceController::class, 'save'])->whereNumber('service')->name('admin.services.update');
        Route::delete('/services/{service}', [BuildingServiceController::class, 'delete'])->whereNumber('service')->name('admin.services.delete');
        Route::get('/bank/connect', [PlaidController::class, 'index'])->name('admin.bank');
        Route::post('/bank/link-token', [PlaidController::class, 'linkToken'])->middleware('throttle:5,1,plaid-link')->name('admin.bank.link');
        Route::post('/bank/exchange', [PlaidController::class, 'exchange'])->middleware('throttle:5,1,plaid-exchange')->name('admin.bank.exchange');
        Route::post('/bank/account', [PlaidController::class, 'select'])->name('admin.bank.select');
        Route::post('/bank/sync', [PlaidController::class, 'sync'])->middleware('throttle:2,5,plaid-sync')->name('admin.bank.sync');
        Route::post('/bank/disconnect', [PlaidController::class, 'disconnect'])->name('admin.bank.disconnect');
        Route::post('/imports', [AdminController::class, 'preview'])->name('admin.preview');
        Route::get('/imports/{batch}', [AdminController::class, 'import'])->whereNumber('batch')->name('admin.import');
        Route::post('/imports/{batch}', [AdminController::class, 'commit'])->whereNumber('batch')->name('admin.commit');
        Route::post('/balance', [AdminController::class, 'checkpoint'])->name('admin.balance');
        Route::get('/payments/new/{household}', [AdminController::class, 'paymentForm'])->whereNumber('household')->name('admin.payment');
        Route::post('/payments', [AdminController::class, 'payment'])->name('admin.payment.store');
        Route::get('/payments/{payment}/allocate', [AdminController::class, 'allocationForm'])->whereNumber('payment')->name('admin.allocations');
        Route::post('/payments/{payment}/allocate', [AdminController::class, 'allocate'])->whereNumber('payment')->name('admin.allocate');
        Route::post('/payments/{payment}/reverse', [AdminController::class, 'reverse'])->whereNumber('payment')->name('admin.reverse');
        Route::post('/assessments', [AdminController::class, 'assessment'])->name('admin.assessment');
        Route::post('/assessments/preview', [AdminController::class, 'assessmentPreview'])->name('admin.assessment.preview');
        Route::post('/assessments/confirm', [AdminController::class, 'assessmentConfirm'])->name('admin.assessment.confirm');
        Route::get('/reconciliation', [ReconciliationController::class, 'index'])->name('admin.reconciliation');
        Route::post('/reconciliation/settings', [ReconciliationController::class, 'settings'])->name('admin.ai.settings');
        Route::post('/reconciliation', [ReconciliationController::class, 'start'])->middleware('throttle:3,10')->name('admin.reconciliation.start');
        Route::get('/reconciliation/{run}', [ReconciliationController::class, 'show'])->whereNumber('run')->name('admin.reconciliation.run');
        Route::post('/reconciliation/suggestions/{suggestion}', [ReconciliationController::class, 'review'])->whereNumber('suggestion')->name('admin.reconciliation.review');
        Route::post('/invoices/{invoice}/void', [AdminController::class, 'void'])->whereNumber('invoice')->name('admin.void');
        Route::post('/residents/{user}', [AdminController::class, 'resident'])->name('admin.resident');
        Route::post('/dues', [AdminController::class, 'dues'])->name('admin.dues');
    });
});
